check_include_file_cxx(any HAVE_HEADER_ANY)
if(NOT HAVE_HEADER_ANY)
    check_include_file_cxx(experimental/any HAVE_HEADER_EXPERIMENTAL_ANY)
    if(NOT HAVE_HEADER_EXPERIMENTAL_ANY)
        check_include_file_cxx(boost/any.hpp HAVE_HEADER_BOOST_ANY_HPP)
        if(NOT HAVE_HEADER_BOOST_ANY_HPP)
            error("Need to have ANY header installed")
        endif()
    endif()
endif()

check_include_file_cxx(optional HAVE_HEADER_OPTIONAL)
if(NOT HAVE_HEADER_OPTIONAL)
    check_include_file_cxx(experimental/optional HAVE_HEADER_EXPERIMENTAL_OPTIONAL)
    if(NOT HAVE_HEADER_EXPERIMENTAL_ANY)
        check_include_file_cxx(boost/optional.hpp HAVE_HEADER_BOOST_OPTIONAL_HPP)
        if(NOT HAVE_HEADER_BOOST_OPTIONAL_HPP)
            error("Need to have OPTIONAL header installed")
        endif()
    endif()
endif()
