check_include_file_cxx(any HAVE_HEADER_ANY)
if(NOT HAVE_HEADER_ANY)
    check_include_file_cxx(experimental/any HAVE_HEADER_EXPERIMENTAL_ANY)
    if(NOT HAVE_HEADER_EXPERIMENTAL_ANY)
        check_include_file_cxx(boost/any.hpp HAVE_HEADER_BOOST_ANY_HPP)
        if(NOT HAVE_HEADER_BOOST_ANY_HPP)
            error("Need to have ANY header installed")
        endif()
    endif()
endif()
